//! Integration tests for `sdkt plugin init`.
//!
//! The first three tests are fast and offline (pure scaffold verification).
//! The last two compile the scaffolded crate against the published `sdkt-audit`
//! from crates.io and are therefore heavier; they pin the acceptance criteria
//! that a scaffolded plugin builds with `--features plugins` and that the
//! placeholder rule is wired (produces a finding) rather than merely compiling.

use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command as StdCommand;
use tempfile::TempDir;

fn sdkt() -> Command {
    Command::cargo_bin("sdkt").unwrap()
}

/// The documented file set generated by `sdkt plugin init`. Must stay in sync
/// with `PLUGIN_SCAFFOLD_FILES` in crates/sdkt-core/src/scaffold.rs.
const DOCUMENTED_FILES: &[&str] = &[
    "Cargo.toml",
    "src/lib.rs",
    "src/plugin_abi.rs",
    "src/plugin_abi_wasm.rs",
    "plugin/plugin.toml",
    "README.md",
    ".gitignore",
];

fn init_project(dir: &Path, name: &str) -> PathBuf {
    let project = dir.join(name);
    sdkt()
        .args(["plugin", "init", project.to_str().unwrap()])
        .assert()
        .success()
        .stdout(predicate::str::contains("Created plugin rule project '"));
    project
}

#[test]
fn plugin_init_creates_documented_layout() {
    let tmp = TempDir::new().unwrap();
    let project = init_project(tmp.path(), "tmp-rule");

    for f in DOCUMENTED_FILES {
        assert!(project.join(f).exists(), "missing scaffolded file: {f}");
    }

    // Rule id is derived from the project name; check() carries TODO markers.
    let lib = fs::read_to_string(project.join("src/lib.rs")).unwrap();
    assert!(
        lib.contains("TMP-RULE-001"),
        "rule id derived from project name"
    );
    assert!(
        lib.contains("TODO"),
        "check() skeleton must carry TODO markers"
    );
    assert!(lib.contains("impl AuditRule"), "must implement AuditRule");

    // README documents build → pack → install → audit with copy-pasteable commands.
    let readme = fs::read_to_string(project.join("README.md")).unwrap();
    assert!(readme.contains("cargo build --release --features plugins"));
    assert!(readme.contains("sdkt plugin pack"));
    assert!(readme.contains("sdkt plugin install"));
    assert!(readme.contains("sdkt audit path/to/contract.rs --rules"));

    // Cargo.toml is a standalone crate wired to the published sdkt-audit.
    let cargo = fs::read_to_string(project.join("Cargo.toml")).unwrap();
    assert!(
        cargo.contains("[workspace]"),
        "standalone crate must declare [workspace]"
    );
    assert!(cargo.contains("sdkt-audit"));
    assert!(cargo.contains("plugins = [\"sdkt-audit/plugins\"]"));
    assert!(cargo.contains("crate-type = [\"rlib\", \"cdylib\"]"));

    // plugin.toml is pre-staged under plugin/ for the pack/install flow.
    let toml = fs::read_to_string(project.join("plugin/plugin.toml")).unwrap();
    assert!(toml.contains("id = \"tmp_rule\""));
    assert!(toml.contains("kind = \"native\""));
    assert!(toml.contains("abi_major = 1"));
}

#[test]
fn plugin_init_rejects_existing_directory() {
    let tmp = TempDir::new().unwrap();
    let project = tmp.path().join("existing");
    fs::create_dir_all(&project).unwrap();

    sdkt()
        .args(["plugin", "init", project.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("already exists"));
}

#[test]
fn plugin_init_json_output() {
    let tmp = TempDir::new().unwrap();
    let project = tmp.path().join("json_proj");

    sdkt()
        .args([
            "plugin",
            "init",
            project.to_str().unwrap(),
            "--format",
            "json",
        ])
        .assert()
        .success()
        .stdout(predicate::str::contains("\"status\":\"created\""));

    assert!(project.join("src/lib.rs").exists());
}

/// The loadable artifact produced for the `tmp-rule` crate (extension varies by
/// platform: `.so` / `.dylib` / `.dll`).
fn find_cdylib_artifact(release_dir: &Path) -> Option<PathBuf> {
    let entries = fs::read_dir(release_dir).ok()?;
    for e in entries.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        if name.contains("tmp_rule")
            && (name.ends_with(".so") || name.ends_with(".dylib") || name.ends_with(".dll"))
        {
            return Some(e.path());
        }
    }
    None
}

#[test]
fn plugin_init_scaffold_builds_with_features_plugins() {
    let tmp = TempDir::new().unwrap();
    let project = init_project(tmp.path(), "tmp-rule");

    let status = StdCommand::new("cargo")
        .args(["build", "--release", "--features", "plugins"])
        .current_dir(&project)
        .status()
        .expect("cargo build failed to execute");
    assert!(
        status.success(),
        "Scaffolded plugin failed to build with --features plugins"
    );

    let artifact = find_cdylib_artifact(&project.join("target/release"));
    assert!(
        artifact.is_some(),
        "cdylib artifact was not produced by the build"
    );
}

#[test]
fn plugin_init_scaffold_rule_produces_finding() {
    // The scaffolded crate ships a unit test asserting the placeholder rule
    // fires (exactly one finding with the derived rule id) on a trivially
    // matching function name and stays silent otherwise. Running `cargo test`
    // therefore proves the rule is wired end-to-end, not just compiling.
    let tmp = TempDir::new().unwrap();
    let project = init_project(tmp.path(), "tmp-rule");

    let status = StdCommand::new("cargo")
        .args(["test", "--features", "plugins"])
        .current_dir(&project)
        .status()
        .expect("cargo test failed to execute");
    assert!(
        status.success(),
        "Scaffolded plugin unit tests (finding production) failed"
    );
}
